- role: Conference Reviewer
  items:
    - AAAI Conference on Artificial Intelligence (AAAI) 2027
    - Neural Information Processing Systems (NeurIPS) 2026
    - Learning for Dynamics and Control (L4DC) 2026
